version: '3'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=gen_password_db
  backend:
    build: ./
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
    ports:
    - 80:8000
    environment:
      - SECRET_KEY=
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
