version: '3'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aleksandrandreev
      - POSTGRES_PASSWORD=w3qxst1ck
      - POSTGRES_DB=gen_password_db
  backend:
    build: ./
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
    ports:
    - 80:8000
    environment:
      - SECRET_KEY=django-insecure-c+ebrz@g)1b4#9axj1vf-86%c@j=29^b0hgddoazm_g9xss4u4
      - POSTGRES_PASSWORD=w3qxst1ck
      - POSTGRES_USER=aleksandrandreev
